package app.gamenative.ui.component.dialog

import androidx.compose.runtime.MutableIntState
import androidx.compose.runtime.MutableState
import app.gamenative.utils.ContainerUtils
import app.gamenative.utils.ManifestComponentHelper
import app.gamenative.utils.ManifestEntry
import com.winlator.box86_64.Box86_64Preset
import com.winlator.contents.ContentProfile
import com.winlator.container.ContainerData
import com.winlator.fexcore.FEXCorePreset

/**
 * State holder for ContainerConfigDialog. Built inside the dialog and passed to each tab composable.
 * Holds references to all mutable state and read-only data so tabs can read/write without 50+ parameters.
 */
class ContainerConfigState(
    val config: MutableState<ContainerData>,
    val graphicsDrivers: MutableState<MutableList<String>>,
    val bionicWineEntries: MutableState<List<String>>,
    val glibcWineEntries: MutableState<List<String>>,
    val wrapperVersions: MutableState<List<String>>,
    val dxvkVersionsAll: MutableState<List<String>>,
    val componentAvailability: MutableState<ManifestComponentHelper.ComponentAvailability?>,
    val showCustomResolutionDialog: MutableState<Boolean>,
    val customResolutionValidationError: MutableState<String?>,
    val vkMaxVersionIndex: MutableIntState,
    val imageCacheIndex: MutableIntState,
    val exposedExtIndices: MutableState<List<Int>>,
    val maxDeviceMemoryIndex: MutableIntState,
    val bionicDriverIndex: MutableIntState,
    val wrapperVersionIndex: MutableIntState,
    val presentModeIndex: MutableIntState,
    val rendererPresentModeIndex: MutableIntState,
    val resourceTypeIndex: MutableIntState,
    val bcnEmulationIndex: MutableIntState,
    val bcnEmulationTypeIndex: MutableIntState,
    val bcnEmulationCacheEnabled: MutableState<Boolean>,
    val disablePresentWaitChecked: MutableState<Boolean>,
    val syncEveryFrameChecked: MutableState<Boolean>,
    val sharpnessEffectIndex: MutableIntState,
    val sharpnessLevel: MutableIntState,
    val sharpnessDenoise: MutableIntState,
    val adrenotoolsTurnipChecked: MutableState<Boolean>,
    val emulator64Index: MutableIntState,
    val emulator32Index: MutableIntState,
    val screenSizeIndex: MutableIntState,
    val customScreenWidth: MutableState<String>,
    val customScreenHeight: MutableState<String>,
    val graphicsDriverIndex: MutableIntState,
    val dxWrapperIndex: MutableIntState,
    val dxvkVersionIndex: MutableIntState,
    val graphicsDriverVersionIndex: MutableIntState,
    val audioDriverIndex: MutableIntState,
    val gpuNameIndex: MutableIntState,
    val renderingModeIndex: MutableIntState,
    val videoMemIndex: MutableIntState,
    val mouseWarpIndex: MutableIntState,
    val externalDisplayModeIndex: MutableIntState,
    val languageIndex: MutableIntState,
    val showEnvVarCreateDialog: MutableState<Boolean>,
    val showAddDriveDialog: MutableState<Boolean>,
    val selectedDriveLetter: MutableState<String>,
    val pendingDriveLetter: MutableState<String>,
    val driveLetterMenuExpanded: MutableState<Boolean>,
    val screenSizes: List<String>,
    val baseGraphicsDrivers: List<String>,
    val dxWrappers: List<String>,
    val dxvkVersionsBase: List<String>,
    val vkd3dVersionsBase: List<String>,
    val audioDrivers: List<String>,
    val presentModes: List<String>,
    val rendererPresentModes: List<String>,
    val resourceTypes: List<String>,
    val bcnEmulationEntries: List<String>,
    val bcnEmulationTypeEntries: List<String>,
    val sharpnessEffects: List<String>,
    val sharpnessDisplayItems: List<String>,
    val renderingModes: List<String>,
    val videoMemSizes: List<String>,
    val mouseWarps: List<String>,
    val externalDisplayModes: List<String>,
    val winCompOpts: List<String>,
    val box64Versions: List<String>,
    val wowBox64VersionsBase: List<String>,
    val box64BionicVersionsBase: List<String>,
    val fexcoreVersionsBase: List<String>,
    val fexcoreTSOPresets: List<String>,
    val fexcoreX87Presets: List<String>,
    val fexcoreMultiblockValues: List<String>,
    val startupSelectionEntries: List<String>,
    val turnipVersions: List<String>,
    val virglVersions: List<String>,
    val zinkVersions: List<String>,
    val vortekVersions: List<String>,
    val adrenoVersions: List<String>,
    val sd8EliteVersions: List<String>,
    val containerVariants: List<String>,
    val bionicWineEntriesBase: List<String>,
    val glibcWineEntriesBase: List<String>,
    val emulatorEntries: List<String>,
    val bionicGraphicsDrivers: List<String>,
    val baseWrapperVersions: List<String>,
    val languages: List<String>,
    val dxvkOptions: ManifestComponentHelper.VersionOptionList,
    val vkd3dOptions: ManifestComponentHelper.VersionOptionList,
    val box64Options: ManifestComponentHelper.VersionOptionList,
    val box64BionicOptions: ManifestComponentHelper.VersionOptionList,
    val wowBox64Options: ManifestComponentHelper.VersionOptionList,
    val fexcoreOptions: ManifestComponentHelper.VersionOptionList,
    val wrapperOptions: ManifestComponentHelper.VersionOptionList,
    val bionicWineOptions: ManifestComponentHelper.VersionOptionList,
    val glibcWineOptions: ManifestComponentHelper.VersionOptionList,
    val dxvkManifestById: Map<String, ManifestEntry>,
    val vkd3dManifestById: Map<String, ManifestEntry>,
    val box64ManifestById: Map<String, ManifestEntry>,
    val wowBox64ManifestById: Map<String, ManifestEntry>,
    val fexcoreManifestById: Map<String, ManifestEntry>,
    val wrapperManifestById: Map<String, ManifestEntry>,
    val bionicWineManifestById: Map<String, ManifestEntry>,
    val glibcWineManifestById: Map<String, ManifestEntry>,
    val gpuCards: Map<Int, ContainerUtils.GpuInfo>,
    val box64Presets: List<Box86_64Preset>,
    val fexcorePresets: List<FEXCorePreset>,
    val gpuExtensions: List<String>,
    val inspectionMode: Boolean,
    val isBionicVariant: Boolean,
    val nonDeletableDriveLetters: Set<String>,
    val availableDriveLetters: List<String>,
    val launchManifestInstall: (ManifestEntry, String, Boolean, ContentProfile.ContentType?, () -> Unit) -> Unit,
    val launchManifestContentInstall: (ManifestEntry, ContentProfile.ContentType, () -> Unit) -> Unit,
    val launchManifestDriverInstall: (ManifestEntry, () -> Unit) -> Unit,
    val launchSteamAppDownload: (Int, String, () -> Unit) -> Unit,
    val getStartupSelectionOptions: () -> List<String>,
    val launchFolderPicker: () -> Unit,
    val getVersionsForDriver: () -> List<String>,
    val getVersionsForBox64: () -> ManifestComponentHelper.VersionOptionList,
    val applyScreenSizeToConfig: () -> Unit,
    val vkd3dForcedVersion: () -> String,
    val currentDxvkContext: () -> ManifestComponentHelper.DxvkContext,
)
